apiVersion: v1
kind: Service
metadata:
  name: backend-nestjs
  labels:
    app: backend-nestjs-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend-nestjs-app
