apiVersion: v1
kind: Service
metadata:
  name: backend-nestjs
  labels:
    app: backend-nestjs-label-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backend-nestjs-depl-app
    app.kubernetes.io/instance: {{ .Release.Name }}
