version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      port: 3001
    ports:
      - "3001:3001"
    command: ["node", "/app/dist/apps/api/main.js"]
    volumes:
      - ./apps/api:/app/apps/api
      - modules:/app/node_modules
  db:
    image: postgres:12-alpine
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend123
      POSTGRES_DB: backend
  adminer:
    image: adminer:4.7.3
    restart: "no"
    ports:
      - "8888:8080"

volumes:
  modules:
  db_data:
