version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      port: 3000
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    volumes:
      - ./apps/api:/app/apps/api
      - modules:/app/node_modules
  db:
  adminer:
volumes:
  modules:
