version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/dev.dockerfile
    command: ["npm", "run", "build", "api", "&&", "npm", "run", "migration:run", "&&", "npm", "run", "start"]
    volumes:
      - .:/app
  db:
  pgadmin:
