version: '3.7'
services:
  api:
    ports:
    - "9229:9229"
    build:
      context: .
      dockerfile: ./apps/api/dev.dockerfile
    volumes:
      - ./apps/api/src:/app/apps/api/src
    command: ["node", "--inspect=0.0.0.0:9229", "-r", "ts-node/register", "apps/api/src/main.ts"]
  db:
  pgadmin:
