version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      port: 3001
      db_host: 'db'
      db_port: 5432
      db_username: backend
      db_password: backend123
      db_name: backend
    ports:
      - "3001:3001"
    command: ["npm", "run", "start"]
  db:
    image: postgres:11.5-alpine
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend123
      POSTGRES_DB: backend
  pgadmin:
    image: dpage/pgadmin4:4.13
    restart: "always"
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: backend
      PGADMIN_DEFAULT_PASSWORD: backend123
volumes:
  modules:
  db_data:
