version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - "db"
    environment:
      API_PORT: 3001
      DB_HOST: 'db'
      DB_PORT: 5432
      DB_USERNAME: backend
      DB_PASSWORD: backend123
      DB_NAME: backend
    ports:
      - "3001:3001"
    command: ["npm", "run", "start:api:with-migrations"]
  db:
    image: postgres:11.5-alpine
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend123
      POSTGRES_DB: backend
  pgadmin:
    image: dpage/pgadmin4:4.14
    restart: "always"
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: backend
      PGADMIN_DEFAULT_PASSWORD: backend123
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 50
volumes:
  modules:
  db_data:
