apiVersion: v1
kind: Secret
metadata:
  name: api-db-credentials
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  DB_HOST: "$API_DB_HOST"
  DB_USERNAME: "$API_DB_USER"
  DB_PASSWORD: "$API_DB_PASSWORD"
  DB_DATABASE: "$API_DB_DATABASE"
